sonar.projectKey=zezuul_po26
sonar.organization=zezuul
sonar.projectName=po26

sonar.sources=zadanie3/src/main/kotlin,zadanie4,zadanie5/client/src,zadanie5/server/src
sonar.exclusions=**/node_modules/**,**/vendor/**,**/build/**,**/dist/**,**/.gradle/**,**/*.pas,**/demos/**,**/zadanie2/**,**/zadanie6/**,**/package-lock.json

sonar.sourceEncoding=UTF-8

# Go (zadanie4)
sonar.go.modules.paths=zadanie4
