sonar.projectKey=zezuul_po26
sonar.organization=zezuul
sonar.projectName=po26

sonar.sources=zadanie3/src/main/kotlin,zadanie4,zadanie5/client/src,zadanie5/server/src
sonar.exclusions=**/node_modules/**,**/vendor/**,**/build/**,**/dist/**,**/*.pas,**/demos/**,**/zadanie2/**,**/zadanie6/codeql-oss/**

sonar.tests=zadanie5/client/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=zadanie5/client/coverage/lcov.info
sonar.sourceEncoding=UTF-8
